// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eewyqxhntjzrouixpxpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVld3lxeGhudGp6cm91aXhweHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MjY1NzcsImV4cCI6MjA3ODEwMjU3N30.PGK2L-nygKBJLA4yVnWff_S8u_-Xg-EtJGAoRlxktog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});